
import React from 'react';
import { Suit, Rank } from './types';

export const SUITS: Suit[] = [Suit.HEARTS, Suit.DIAMONDS, Suit.CLUBS, Suit.SPADES];
export const RANKS: Rank[] = [
  Rank.TWO, Rank.THREE, Rank.FOUR, Rank.FIVE, Rank.SIX,
  Rank.SEVEN, Rank.EIGHT, Rank.NINE, Rank.TEN,
  Rank.JACK, Rank.QUEEN, Rank.KING, Rank.ACE
];

export const SUIT_ICONS: Record<Suit, React.ReactNode> = {
  [Suit.HEARTS]: <span className="text-red-500">♥</span>,
  [Suit.DIAMONDS]: <span className="text-red-500">♦</span>,
  [Suit.CLUBS]: <span className="text-black">♣</span>,
  [Suit.SPADES]: <span className="text-black">♠</span>,
};

export const SUIT_COLORS: Record<Suit, string> = {
  [Suit.HEARTS]: 'text-red-600',
  [Suit.DIAMONDS]: 'text-red-600',
  [Suit.CLUBS]: 'text-gray-900',
  [Suit.SPADES]: 'text-gray-900',
};

export const TRANSLATIONS = {
  ZH: {
    title: "小鸢乐园之疯狂8点",
    subtitle: "疯狂 8 点",
    start: "开始游戏",
    restart: "重开一局",
    home: "返回首页",
    deck: "牌堆",
    playerTurn: "你的回合",
    aiTurn: "AI 的回合",
    draw: "摸牌",
    pass: "跳过",
    selectSuit: "选择下一个花色",
    win: "你赢了！",
    lose: "再接再厉！",
    welcome: "欢迎来到疯狂8点！",
    invalidMove: "无效的出牌！请选择相同花色或点数的牌。",
    shuffling: "洗牌中...",
    emptyDeck: "摸牌堆已空，跳过回合！",
    playerPlayed: "你打出了",
    aiPlayed: "AI 打出了",
    playerDrew: "你摸了一张牌。",
    aiDrew: "AI 摸了一张牌。",
    hearts: "红心",
    diamonds: "方块",
    clubs: "梅花",
    spades: "黑桃",
    back: "返回",
    alreadyDrawn: "每回合只能摸一张牌！",
  },
  EN: {
    title: "Yuan's Playground Crazy Eight",
    subtitle: "Crazy 8",
    start: "Start Game",
    restart: "Restart",
    home: "Home",
    deck: "Deck",
    playerTurn: "Your Turn",
    aiTurn: "AI Turn",
    draw: "Draw",
    pass: "Pass",
    selectSuit: "Select Next Suit",
    win: "You Win!",
    lose: "Keep it up!",
    welcome: "Welcome to Crazy 8!",
    invalidMove: "Invalid move! Match suit or rank.",
    shuffling: "Shuffling...",
    emptyDeck: "Deck empty, skipping turn!",
    playerPlayed: "You played",
    aiPlayed: "AI played",
    playerDrew: "You drew a card.",
    aiDrew: "AI drew a card.",
    hearts: "Hearts",
    diamonds: "Diamonds",
    clubs: "Clubs",
    spades: "Spades",
    back: "Back",
    alreadyDrawn: "Only one draw per turn!",
  },
  ES: {
    title: "El Patio de Yuan: Ocho Loco",
    subtitle: "Ocho Loco",
    start: "Empezar",
    restart: "Reiniciar",
    home: "Inicio",
    deck: "Mazo",
    playerTurn: "Tu Turno",
    aiTurn: "Turno IA",
    draw: "Robar",
    pass: "Pasar",
    selectSuit: "Selecciona Palo",
    win: "¡Ganaste!",
    lose: "¡Sigue así!",
    welcome: "¡Bienvenido a Ocho Loco!",
    invalidMove: "¡Movimiento inválido!",
    shuffling: "Barajando...",
    emptyDeck: "¡Mazo vacío!",
    playerPlayed: "Jugaste",
    aiPlayed: "IA jugó",
    playerDrew: "Robaste una carta.",
    aiDrew: "IA robó una carta.",
    hearts: "Corazones",
    diamonds: "Diamantes",
    clubs: "Tréboles",
    spades: "Picas",
    back: "Volver",
    alreadyDrawn: "¡Solo un robo por turno!",
  }
};
